http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
core.autocrlf=input
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Sublime Text 3\\subl.exe" -w
add.interactive.usebuiltin=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=uchiha1tachi
user.email=izestkov40@gmail.com
core.editor=nano
merge.tool=vimdiff
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.test.url=git@github.com:uchiha1tachi/test.git
remote.test.fetch=+refs/heads/*:refs/remotes/test/*
remote.origin.url=git@github.com:uchiha1tachi/1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
